(ns leihs.admin.common.icons
  (:require
   ["@fortawesome/free-brands-svg-icons" :as brands]
   ["@fortawesome/free-solid-svg-icons" :as solids]
   ["@fortawesome/react-fontawesome" :as fa-react-fontawesome]))

(def FontAwesomeIcon (.-FontAwesomeIcon fa-react-fontawesome))

(defn add [] [:> FontAwesomeIcon {:icon solids/faPlusCircle :className ""}])
(defn admin [] [:> FontAwesomeIcon {:icon solids/faWrench :className ""}])
(defn arrow-right-arrow-left [] [:> FontAwesomeIcon {:icon solids/faArrowRightArrowLeft :className ""}])
(defn award [] [:> FontAwesomeIcon {:icon solids/faAward :className ""}])
(defn back [] [:> FontAwesomeIcon {:icon solids/faArrowLeft :className ""}])
(defn building [] [:> FontAwesomeIcon {:icon solids/faBuilding :className ""}])
(defn chart-column [] [:> FontAwesomeIcon {:icon solids/faChartColumn :className ""}])
(defn chevron-left [] [:> FontAwesomeIcon {:icon solids/faChevronLeft :className ""}])
(defn chevron-right [] [:> FontAwesomeIcon {:icon solids/faChevronRight :className ""}])
(defn code-pull-request [] [:> FontAwesomeIcon {:icon solids/faCodePullRequest :className ""}])
(defn delegation [] [:> FontAwesomeIcon {:icon solids/faHandsHelping :className ""}])
(defn delegations [] [:> FontAwesomeIcon {:icon solids/faHandsHelping :className ""}])
(defn delete [] [:> FontAwesomeIcon {:icon solids/faTimes :className ""}])
(defn edit [] [:> FontAwesomeIcon {:icon solids/faEdit :className ""}])
(defn email [] [:> FontAwesomeIcon {:icon solids/faEnvelope :className ""}])
(defn file-export [] [:> FontAwesomeIcon {:icon solids/faFileExport :className ""}])
(defn github [] [:> FontAwesomeIcon {:icon brands/faGithubSquare :className ""}])
(defn group [] [:> FontAwesomeIcon {:icon solids/faUsers :className ""}])
(defn groups [] [:> FontAwesomeIcon {:icon solids/faUsers :className ""}])
(defn home [] [:> FontAwesomeIcon {:icon solids/faHome :className ""}])
(defn inventory-pool [] [:> FontAwesomeIcon {:icon solids/faCube :className ""}])
(defn inventory-pools [] [:> FontAwesomeIcon {:icon solids/faCubes :className ""}])
(defn key-icon [] [:> FontAwesomeIcon {:icon solids/faKey :className ""}])
(defn language [] [:> FontAwesomeIcon {:icon solids/faLanguage :className ""}])
(defn list-icon [] [:> FontAwesomeIcon {:icon solids/faList :className ""}])
(defn mail-template [] [:> FontAwesomeIcon {:icon solids/faEnvelope :className ""}])
(defn opening-times [] [:> FontAwesomeIcon {:icon solids/faDoorOpen :className ""}])
(defn paper-plane [] [:> FontAwesomeIcon {:icon solids/faPaperPlane :className ""}])
(defn rooms [] [:> FontAwesomeIcon {:icon solids/faPersonShelter :className ""}])
(defn save [] [:> FontAwesomeIcon {:icon solids/faSave :className ""}])
(defn shield-halved [] [:> FontAwesomeIcon {:icon solids/faShieldHalved :className ""}])
(defn suppliers [] [:> FontAwesomeIcon {:icon solids/faTruck :className ""}])
(defn table-list [] [:> FontAwesomeIcon {:icon solids/faTableList :className ""}])
(defn toggle-off [] [:> FontAwesomeIcon {:icon solids/faToggleOff :className "fa-xl"}])
(defn toggle-on [] [:> FontAwesomeIcon {:icon solids/faToggleOn :className "fa-xl"}])
(defn user [] [:> FontAwesomeIcon {:icon solids/faUser :className ""}])
(defn users [] [:> FontAwesomeIcon {:icon solids/faUserFriends :className ""}])
(defn view [] [:> FontAwesomeIcon {:icon solids/faEye :className ""}])
(defn waiting [& {:keys [size] :or {size "1x"}}] [:> FontAwesomeIcon {:icon solids/faCircleNotch :className "" :spin true :size size}])
(defn warehouse [] [:> FontAwesomeIcon {:icon solids/faWarehouse :className ""}])
(defn clock-rotate-left [] [:> FontAwesomeIcon {:icon solids/faClockRotateLeft :className ""}])
(defn categories [] [:> FontAwesomeIcon {:icon solids/faBarsStaggered :className ""}])
(defn info [] [:> FontAwesomeIcon {:icon solids/faCircleInfo :className ""}])
